name: "Build CR Droid 15 kernel on Taimen."              # Description of the workflow.
on:
  push:
    branches: "15.0"                                  # Branch to build.
  workflow_dispatch:                                  # Allow to manually trigger workflow.
jobs:
  build:
    name: "Build CR Droid 15 kernel"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout kernel source"                  # Clone the kernel source.
      uses: actions/checkout@v2
    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
      uses: lemniskett/android-kernel-actions@master
      with:
        arch: arm64                                   # Specify arch
        compiler: clang                               # Specify toolchain to use
        defconfig: wahoo_defconfig                    # Specify defconfig to use
        image: Image.gz-dtb                           # Specify final build file

