name: Build CR Droid 15 kernel for Taimen
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Flouzr/android_kernel_google_wahoo
          kernel-dir: kernel
          kernel-branch: "15.0"
          config: wahoo_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          #ksu: true
          #ksu-version: main
          android-version: 15
          aosp-clang-version: r536225
          disable-lto: true
          #anykernel3: true
