name: Build crDroid 15.0 - Pixel 2 XL

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Flouzr/android_kernel_google_wahoo
          kernel-branch: "15.0"
          config: wahoo_defconfig
          arch: arm64
          aosp-gcc: false
          android-version: 8
          other-clang-url: "https://gitlab.com/kei-space/clang/r536225.git"
          other-clang-branch: master
